version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,Content-Type,Authorization
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
    ports:
      - "9200:9200"
    networks:
      - es-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "8000:8000"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge
